stages:
  - test
  - lint


test-lab3:
  stage: test
  image:
    name: ryukzak/python-tools
    entrypoint: [""]
  script:
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt
    - coverage run -m pytest --verbose
    - find . -type f -name "*.py" | xargs -t coverage report


lint-lab3:
  stage: lint
  image:
    name: ryukzak/python-tools
    entrypoint: [""]
  script:
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt
    - ruff format --check .
    - poetry run ruff check .

